### ISSUE TITLE
Bug in json-File for Intel 520 Series SSDs

### ISSUE THREAD

**Issue by DanielBloemerViaprinto** [thomas-krenn/check_smart_attributes#1]
There are two VALUES for the SSD mentioned above which seem to be incorrect.
Test runs into Error, this change helped:
@@ -41,8 +41,8 @@
 				"5" : "RAW_VALUE", # Reallocated sector count
 				"9" : "RAW_VALUE", # Power on hours
 				"12": "RAW_VALUE", # Power cycle counts
-				"171" : "RAW_VALUE", # Program fail count
-				"172" : "RAW_VALUE", # Erase fail count
+				"171" : "VALUE", # Program fail count
+				"172" : "VALUE", # Erase fail count
 				"184" : "VALUE", # End-to-End Error Detection
 				"187" : "RAW_VALUE", # Uncorrectable Error Count
 				"190" : "RAW_VALUE", # Temperature case

**Comment by gschoenberger** [comment]
Hi Daniell,
that's correct!
* http://download.intel.com/newsroom/kits/ssd/pdfs/intel_ssd_520_product_spec_325968.pdf
Fixed by commit 591d5f4f04ff9b23b47e6699885b90c1b5ab2a94

Thanks for the hint!
