### ISSUE TITLE
NRPE Error: device was not found in smartdb JSON file.

### ISSUE THREAD

**Issue by ecenica** [thomas-krenn/check_smart_attributes#2]
Hi,

We're seeing the error below when we run the plugin via NRPE from the Icinga server:

`NRPE Error: device was not found in smartdb JSON file.`

- The device is in check_smartdb.json
- Running the check_smart_attributes command on the remote server works and provides the expected result.

Any suggestions?

Thanks,

Jeff

**Comment by gschoenberger** [comment]
Can you please post:
* Command definition of NRPE
* The debug Output of NRPE (to check that the right commnand is called)
* The local command the works
** Add -vvv to get some debug infos

THX, Georg

**Comment by ecenica** [comment]
Hi Georg,

Thanks for the quick reply. Details below:

- Command definition of NRPE:

`command[check_smart_attributes]=/usr/lib/nagios/plugins/check_smart_attributes -dbj /etc/nagios-plugins/config/check_smartdb.json -d /dev/sdc`

- The debug Output of NRPE (to check that the right commnand is called):

``` 
May  3 18:05:48 host nrpe[3828]: Handling the connection...
May  3 18:05:48 host nrpe[3828]: Host is asking for command 'check_smart_attributes' to be run...
May  3 18:05:48 host nrpe[3828]: Running command: /usr/lib/nagios/plugins/check_smart_attributes -dbj /etc/nagios-plugins/config/check_smartdb.json -d /dev/sdc
May  3 18:05:48 host nrpe[3828]: Command completed with return code 3 and output: Error: device was not found in smartdb JSON file.
May  3 18:05:48 host nrpe[3828]: Return Code: 3, Output: Error: device was not found in smartdb JSON file.
```

- The local command the works ** Add -vvv to get some debug infos:

```
bash-4.1$ /usr/lib/nagios/plugins/check_smart_attributes -dbj /etc/nagios-plugins/config/check_smartdb.json -d /dev/sdc -vvv
OK (sdc) |'sdc_Temperature_Celsius'=35
sdc_Raw_Read_Error_Rate = 200 (VALUE)
sdc_Spin_Up_Time = 100 (VALUE)
sdc_Start_Stop_Count = 1 (RAW_VALUE)
sdc_Reallocated_Sector_Ct = 0 (RAW_VALUE)
sdc_Seek_Error_Rate = 0 (RAW_VALUE)
sdc_Power_On_Hours = 529 (RAW_VALUE)
sdc_Spin_Retry_Count = 0 (RAW_VALUE)
sdc_Calibration_Retry_Count = 0 (RAW_VALUE)
sdc_Power_Cycle_Count = 1 (RAW_VALUE)
sdc_Load_Cycle_Count = 90 (RAW_VALUE)
sdc_Temperature_Celsius = 35 (RAW_VALUE)
sdc_Reallocated_Event_Count = 0 (RAW_VALUE)
sdc_Current_Pending_Sector = 0 (RAW_VALUE)
sdc_Offline_Uncorrectable = 0 (RAW_VALUE)
sdc_UDMA_CRC_Error_Count = 0 (RAW_VALUE)
sdc_Multi_Zone_Error_Rate = 0 (RAW_VALUE)
======================================== 
Device: /dev/sdc

================= 
Thresholds:
197: [0,10]
11: [0,10]
3: [32:,22:]
198: [0,10]
199: [0,10]
1: [62:,52:]
196: [0,10]
10: [0,10]
5: [10,20]
================= 
Performance Value IDs:
[194]
================= 
Begin of smartctl output:
```

I've cut the rest as it's the expected smartctl output...

Really stumped. NRPE works fine for our other plugins.

Thanks for your help.

Jeff

**Comment by ecenica** [comment]
Hi Georg,

Ran through everything from scratch and we have resolved it.

We're running CentOS so adding the below to /etc/sudoers.d fixed it.

```
Defaults: nagios !requiretty
nagios    ALL=(root)      NOPASSWD: /usr/sbin/smartctl
```

Thanks for your help!

Jeff
