### ISSUE TITLE
Detect if device path is symlink and read it

### ISSUE THREAD

**Issue by MichalMMac** [thomas-krenn/check_smart_attributes#29]
I've been playing with your script on macOS. Very good work btw.

I run into minor problem. On macOS device path `/dev/diskX` is not guaranteed to point to the same device after next boot. We have handy symlinks in `/var/run/disk/by-serial` but `smartctl` does not like symlinks to devices -> `"No such device" for device...`. Simple solution would be running `readlink` in subshell:
```
check_smart_attributes -d `readlink /var/run/disk/by-serial/xyz`
```
However I am unable to do this with Icinga2 because command is probably invoked directly.

My final solution is to patch `check_smart_attributes` (My Perl skills are limited to say the least).

```
else{
      if( -l $device ) {
        $device = readlink( $device )
      }
     @output = `$smartctl -a $device`;
}
```
Is this something worth impelmenting on your side?

I can think of two ways:

- If device path is symlink, follow it automatically always.
- Add parameter option enabling symlink following

**Comment by gschoenberger** [comment]
I think we can follow the link if we ensure to get the absolute path back. Can you test the latest commit?
f1352cb34396dd4c74160218996af40160d5f447

**Comment by MichalMMac** [comment]
Work correctly in my setup.
Thank you :-)
