### ISSUE TITLE
does not work with megaraid 

### ISSUE THREAD

**Issue by george2asenov** [thomas-krenn/check_smart_attributes#33]
for megaraid controllers smartctl need the device to be 
sat+megaraid,ID/dev/sdX
otherwise smartctl does not find the device

from smartctl --help
> Specify device type to one of: ata, scsi, sat[,auto][,N][+TYPE], usbcypress[,X], usbjmicron[,x][,N], usbsunplus, marvell, areca,N/E, 3ware,N, hpt,L/M/N, megaraid,N, cciss,N, auto, test
                               background, sasphy[,reset], sataphy[,reset],

**Comment by gschoenberger** [comment]
So "sat+" is really required? You have tried "-d megaraidID,/dev/sdX"?

**Comment by george2asenov** [comment]
Yes I tried -d megaraidID,/dev/sdX and also adding "-O sat ", "-O "+sat"" and nothing helped.
everything worked after editing "sub getSmartctl{
...
...
elsif($device =~ /^(megaraid[0-9]+),(\/dev\/[a-zA-Z]+)$/){
...
...
from "@output = `$smartctl -a -d $megaDevice $devicePath`;" to "@output = `$smartctl -a -d sat+$megaDevice $devicePath`;"
...
...

And then found another issue.
In -ucfgj config file the device should be set as "/dev/megaraidID" not as "megaraidID,/dev/sdX" which isn't documented (or i didn't found it)

**Comment by gschoenberger** [comment]
Can you test commit 3ad21d014989e51cc2a2da79469d42b5a2c180cc ?
It is now possible to pass 'sat+' as extra Option, the -O "sat+" should be working now correctly!
Feedback appreciated,
TXH Georg

**Comment by gschoenberger** [comment]
I am closing this as issue #44 is currently open.
