### ISSUE TITLE
Proposition: use valid json

### ISSUE THREAD

**Issue by unknown321** [thomas-krenn/check_smart_attributes#34]
Currently, script cannot be used on RHEL-based systems due to Config::JSON dependency without installing a lot of side modules from CPAN. For example, on Centos 7 you need to install a side repo - https://harbottle.gitlab.io/epmel/7/ in order to get dependencies (ie perl(Moo)) required by Config::JSON. I haven't been able to install it properly on Centos 6 at all.

How about changing the format of check_smartdb.json (with corresponding changes in the script)?

```
"5" : {"value": "RAW_VALUE", "comment": "Re-allocated Sector Count"},
"9" : {"value": "RAW_VALUE", "comment": "Power-On Hours Count"}
```

instead of

```
"5" : "RAW_VALUE", # Re-allocated Sector Count
"9" : "RAW_VALUE", # Power-On Hours Count
```

Pros: 
  - fewer dependencies (fewer things that could be broken)
  - smartdb can be reused in similar projects
  - more distributions to cover.

Cons: 
  - a slightly bigger check_smartdb.json

**Comment by rjhenry** [comment]
I have a PR open for this one - #77. Give it a look over, and a test if you could!

**Comment by gschoenberger** [comment]
@rjhenry @unknown321 THX a lot for your PULL request, I am looking at it and also testing it.
If we switch to valid JSON, I guess we should also drop the Config::JSON dependency?
What perl JSON parser should we then use so the plugin can be used easily on RHEL?

**Comment by rjhenry** [comment]
The most sensible substitution as far as I can tell would be https://metacpan.org/release/JSON, which is available from RH's base repo as perl-JSON.

Once the merge to use valid JSON in place is in place, I'll likely get some work done to migrate from Config::JSON to JSON.

**Comment by gschoenberger** [comment]
I have merged your branch and fixed some more errors in the JSON, I have pushed my most recent version.
Can you now check how to use the alternative JSON library in place?

**Comment by apollo13** [comment]
Hi @gschoenberger I am currently deploying the following patch for Centos and it seems to work fine: https://github.com/apollo13/check_smart_attributes/compare/master...apollo13-patch-1 

The patch uses perl-JSON as suggested by @rjhenry

**Comment by apollo13** [comment]
FWIW, I have no clue how perl works and just copied stuff around, if my approach works for you feel free to take it & use it as you see fit.

**Comment by gschoenberger** [comment]
Basically I have just taken a more readable version of your patch :+1:

**Comment by rjhenry** [comment]
Hi @apollo13 - just wanted to say thanks! I've had a fair bit of stuff going on the last month or so, and hadn't had any opportunity to really work with this.

Cheers!
