### ISSUE TITLE
[REQUEST] Add option to use regexp for device

### ISSUE THREAD

**Issue by Rohlik** [thomas-krenn/check_smart_attributes#47]
Similar script for check S.M.A.R.T. at https://github.com/Napsty/check_smart/blob/master/check_smart.pl have option to specify drives with regexp like `-g "/dev/[hs]d[a-z]"` and it is very handy. It would be fine integrate this feature in your script too.

**Comment by tniedermeier** [comment]
Hi @Rohlik,
thank you for your request, we'll take a look at it.

Best regards,
Thomas

**Comment by gschoenberger** [comment]
Can you test commit 311b302c6fe797142239e357130ed6804a2a1826 ?
./check_smart_attributes -dbj ./check_smartdb.json -r '/dev/sd[a-z]$'

**Comment by Rohlik** [comment]
@gschoenberger I have problem with `Config/JSON.pm` dependencies. It is not in standard centos/RHEL repo.
So I cannot test it, sorry.

**Comment by tniedermeier** [comment]
Parameter works fine, closing issue.
