### ISSUE TITLE
[Wishlist] detect failed smart selftests

### ISSUE THREAD

**Issue by huckley** [thomas-krenn/check_smart_attributes#49]
Dont know if this is out of scope of this check, but is there a possibility to check for failed smart selftests?

**Comment by gschoenberger** [comment]
Do you have any output of smartctl with a failed selftest? Then we could look how to check and parse these errors.

**Comment by ssams** [comment]
I just saw this issue, and whilst I personally wouldn't have a use case for the requested feature I can provide an example output for a failed test as requested:

Output of the command `smartctl -x /dev/sdc`, the last short selftest failed with errors. Status is visible in the general SMART values (section "Self-test execution status") and of course more detailed in the self-test log - line 1 in the log refers to the latest test, the attached output also includes several older log entries from failed tests.
[output_smartctl.txt](https://github.com/thomas-krenn/check_smart_attributes/files/2846125/output_smartctl.txt)

**Comment by gschoenberger** [comment]
Do we have to `-x` or is the execution status also visible with `-a`?
Currently we are using `-a` in the plugin, so if the test execution is only visible with `-x` we have to consider a second `smartctl` call or switch from `-a` to `-x` -> that would require to check the attribute parsing logic again...

**Comment by gschoenberger** [comment]
Maybe we should use `sudo smartctl -l selftest /dev/sda` to get the test just.
That would make parsing the test results easier...

**Comment by ssams** [comment]
Looks like the relevant data is also available in the output of `smartctl -a`: 
[smartctl_a.txt](https://github.com/thomas-krenn/check_smart_attributes/files/2850141/smartctl_a.txt)

For reference, here's also the output of `smartctl -l selftest` for the failing disk: 
[smartctl_selftest.txt](https://github.com/thomas-krenn/check_smart_attributes/files/2850142/smartctl_selftest.txt)

**Comment by gschoenberger** [comment]
I would suggest to not check SMART self-tests. As these tests are run for each individual disk on demand it would be better to check the result of the test after the test run.
