### ISSUE TITLE
[REQUEST] Add Hitachi HUA722010CLA330 to check_smartdb.json

### ISSUE THREAD

**Issue by ChiyoDraconis** [thomas-krenn/check_smart_attributes#55]
Hello, 

please add more information to Hitachi HUA722010CLA330 to check_smartdb.json

I get only the following information only right now:

./check_smart_attributes -d /dev/sg2 -O sat -dbj /etc/nagios-plugins/config/check_smartdb.json
Warning (sg2) [sg2_Reallocated_Event_Count = Warning]|'sg2_Temperature_Celsius'=30

smartctl gives the following output:

smartctl --all /dev/sg2
smartctl 6.4 2014-10-07 r4002 [x86_64-linux-3.16.0-6-amd64] (local build)
Copyright (C) 2002-14, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF INFORMATION SECTION ===
Model Family:     Hitachi Ultrastar A7K2000
Device Model:     Hitachi HUA722010CLA330
Serial Number:    JPW9J0N20HKL6C
LU WWN Device Id: 5 000cca 3a8c71396
Firmware Version: JP4OA3EA
User Capacity:    1.000.204.886.016 bytes [1,00 TB]
Sector Size:      512 bytes logical/physical
Rotation Rate:    7200 rpm
Form Factor:      3.5 inches
Device is:        In smartctl database [for details use: -P show]
ATA Version is:   ATA8-ACS T13/1699-D revision 4
SATA Version is:  SATA 2.6, 3.0 Gb/s
Local Time is:    Wed Oct 24 14:11:31 2018 CEST
SMART support is: Available - device has SMART capability.
SMART support is: Enabled

=== START OF READ SMART DATA SECTION ===
SMART Status not supported: Incomplete response, ATA output registers missing
SMART overall-health self-assessment test result: PASSED
Warning: This result is based on an Attribute check.

General SMART Values:
Offline data collection status:  (0x84) Offline data collection activity
                                        was suspended by an interrupting command from host.
                                        Auto Offline Data Collection: Enabled.
Self-test execution status:      (   0) The previous self-test routine completed
                                        without error or no self-test has ever
                                        been run.
Total time to complete Offline
data collection:                ( 9396) seconds.
Offline data collection
capabilities:                    (0x5b) SMART execute Offline immediate.
                                        Auto Offline data collection on/off support.
                                        Suspend Offline collection upon new
                                        command.
                                        Offline surface scan supported.
                                        Self-test supported.
                                        No Conveyance Self-test supported.
                                        Selective Self-test supported.
SMART capabilities:            (0x0003) Saves SMART data before entering
                                        power-saving mode.
                                        Supports SMART auto save timer.
Error logging capability:        (0x01) Error logging supported.
                                        General Purpose Logging supported.
Short self-test routine
recommended polling time:        (   1) minutes.
Extended self-test routine
recommended polling time:        ( 157) minutes.
SCT capabilities:              (0x003d) SCT Status supported.
                                        SCT Error Recovery Control supported.
                                        SCT Feature Control supported.
                                        SCT Data Table supported.

SMART Attributes Data Structure revision number: 16
Vendor Specific SMART Attributes with Thresholds:
ID# ATTRIBUTE_NAME          FLAG     VALUE WORST THRESH TYPE      UPDATED  WHEN_FAILED RAW_VALUE
  1 Raw_Read_Error_Rate     0x000b   100   100   016    Pre-fail  Always       -       0
  2 Throughput_Performance  0x0005   137   137   054    Pre-fail  Offline      -       91
  3 Spin_Up_Time            0x0007   122   122   024    Pre-fail  Always       -       310 (Average 311)
  4 Start_Stop_Count        0x0012   100   100   000    Old_age   Always       -       25
  5 Reallocated_Sector_Ct   0x0033   100   100   005    Pre-fail  Always       -       2
  7 Seek_Error_Rate         0x000b   100   100   067    Pre-fail  Always       -       0
  8 Seek_Time_Performance   0x0005   138   138   020    Pre-fail  Offline      -       31
  9 Power_On_Hours          0x0012   096   096   000    Old_age   Always       -       32761
 10 Spin_Retry_Count        0x0013   100   100   060    Pre-fail  Always       -       0
 12 Power_Cycle_Count       0x0032   100   100   000    Old_age   Always       -       11
192 Power-Off_Retract_Count 0x0032   100   100   000    Old_age   Always       -       147
193 Load_Cycle_Count        0x0012   100   100   000    Old_age   Always       -       147
194 Temperature_Celsius     0x0002   200   200   000    Old_age   Always       -       30 (Min/Max 19/34)
196 Reallocated_Event_Count 0x0032   100   100   000    Old_age   Always       -       2
197 Current_Pending_Sector  0x0022   100   100   000    Old_age   Always       -       0
198 Offline_Uncorrectable   0x0008   100   100   000    Old_age   Offline      -       0
199 UDMA_CRC_Error_Count    0x000a   200   200   000    Old_age   Always       -       0

SMART Error Log Version: 0
No Errors Logged

SMART Self-test log structure revision number 1
Num  Test_Description    Status                  Remaining  LifeTime(hours)  LBA_of_first_error
# 1  Extended offline    Completed without error       00%     32641         -
# 2  Short offline       Completed without error       00%     32639         -
# 3  Short offline       Completed without error       00%         0         -

SMART Selective self-test log data structure revision number 1
 SPAN  MIN_LBA  MAX_LBA  CURRENT_TEST_STATUS
    1        0        0  Not_testing
    2        0        0  Not_testing
    3        0        0  Not_testing
    4        0        0  Not_testing
    5        0        0  Not_testing
Selective self-test flags (0x0):
  After scanning selected spans, do NOT read-scan remainder of disk.
If Selective self-test is pending on power-up, resume after 0 minute delay.

I was informed by TK Support to create an issue here for this request. 

Thank you in advance

**Comment by tniedermeier** [comment]
Hello @ChiyoDraconis,
thank you for your issue. We currently only set the drive temperature as performance data for all hard disk entries in our database.
Could you please give us an output of the plugin in verbose mode? An output with -v and a second one with -vvv. Then the plugin prints out more information about your hard disk.
Which values would you like to have as performance data? Not every value makes sense as performance data. A SSD has more appropriate SMART values which can be selected as performance data.

Best regards,
Thomas

**Comment by ChiyoDraconis** [comment]
Hello @tniedermeier,
thank you for your fast reply. As you mentioned here the verbose outputs.

./check_smart_attributes -d /dev/sg2 -O sat -dbj /etc/nagios-plugins/config/check_smartdb.json -v
Warning (sg2) [sg2_Reallocated_Event_Count = Warning (2)]|'sg2_Temperature_Celsius'=30

./check_smart_attributes -d /dev/sg2 -O sat -dbj /etc/nagios-plugins/config/check_smartdb.json -vv
Warning (sg2) [sg2_Reallocated_Event_Count = Warning (2)]|'sg2_Temperature_Celsius'=30
sg2_Raw_Read_Error_Rate = 100 (VALUE)
sg2_Throughput_Performance = 137 (VALUE)
sg2_Spin_Up_Time = 122 (VALUE)
sg2_Start_Stop_Count = 25 (RAW_VALUE)
sg2_Reallocated_Sector_Ct = 2 (RAW_VALUE)
sg2_Seek_Error_Rate = 0 (RAW_VALUE)
sg2_Seek_Time_Performance = 138 (VALUE)
sg2_Power_On_Hours = 32785 (RAW_VALUE)
sg2_Spin_Retry_Count = 0 (RAW_VALUE)
sg2_Power_Cycle_Count = 11 (RAW_VALUE)
sg2_Load_Cycle_Count = 147 (RAW_VALUE)
sg2_Temperature_Celsius = 30 (RAW_VALUE)
sg2_Reallocated_Event_Count = 2 (RAW_VALUE)
sg2_Current_Pending_Sector = 0 (RAW_VALUE)
sg2_Offline_Uncorrectable = 0 (RAW_VALUE)
sg2_UDMA_CRC_Error_Count = 0 (RAW_VALUE)

As perfomancedata relevant are for me:

Spinuptime, Raw read error rate, seek error rate, temperature, scan error rate and reallocated sector count

**Comment by tniedermeier** [comment]
Hi @ChiyoDraconis,

sorry for my delayed reply. To address individual requirements, please feel free to add these additional attributes to a custom check_smartdb.json file. Using the -dbj parameter with the check_smart_attributes plugin you can select a custom database file. We would like to keep the standard database more generic, so it fits the majority of users.

Best regards,
Thomas
