### ISSUE TITLE
[REQUEST] Add SSDSC2BX80 check_smart_db.json

### ISSUE THREAD

**Issue by ChiyoDraconis** [thomas-krenn/check_smart_attributes#60]
Hello,

please add more information to Intel SSDSC2BX80 to check_smartdb.json

smartctl gives the following output:

smartctl --all /dev/sg2
smartctl 5.41 2011-06-09 r3365 [x86_64-linux-3.2.0-4-amd64] (local build)
Copyright (C) 2002-11 by Bruce Allen, http://smartmontools.sourceforge.net

=== START OF INFORMATION SECTION ===
Model Family:     Intel 730 and DC S35x0/3610/3700 Series SSDs
Device Model:     INTEL SSDSC2BX800G4
Serial Number:    BTHC605406H3800NGN
LU WWN Device Id: 5 5cd2e4 04c1bc4e9
Firmware Version: G2010140
User Capacity:    800.166.076.416 bytes [800 GB]
Sector Sizes:     512 bytes logical, 4096 bytes physical
Device is:        In smartctl database [for details use: -P show]
ATA Version is:   8
ATA Standard is:  ACS-2 revision 3
Local Time is:    Fri Oct 26 11:05:54 2018 CEST
SMART support is: Available - device has SMART capability.
SMART support is: Enabled

=== START OF READ SMART DATA SECTION ===
SMART overall-health self-assessment test result: PASSED

General SMART Values:
Offline data collection status:  (0x02) Offline data collection activity
                                        was completed without error.
                                        Auto Offline Data Collection: Disabled.
Self-test execution status:      (   0) The previous self-test routine completed
                                        without error or no self-test has ever
                                        been run.
Total time to complete Offline
data collection:                (    2) seconds.
Offline data collection
capabilities:                    (0x79) SMART execute Offline immediate.
                                        No Auto Offline data collection support.
                                        Suspend Offline collection upon new
                                        command.
                                        Offline surface scan supported.
                                        Self-test supported.
                                        Conveyance Self-test supported.
                                        Selective Self-test supported.
SMART capabilities:            (0x0003) Saves SMART data before entering
                                        power-saving mode.
                                        Supports SMART auto save timer.
Error logging capability:        (0x01) Error logging supported.
                                        General Purpose Logging supported.
Short self-test routine
recommended polling time:        (   1) minutes.
Extended self-test routine
recommended polling time:        (   2) minutes.
Conveyance self-test routine
recommended polling time:        (   2) minutes.
SCT capabilities:              (0x003d) SCT Status supported.
                                        SCT Error Recovery Control supported.
                                        SCT Feature Control supported.
                                        SCT Data Table supported.

SMART Attributes Data Structure revision number: 1
Vendor Specific SMART Attributes with Thresholds:
ID# ATTRIBUTE_NAME          FLAG     VALUE WORST THRESH TYPE      UPDATED  WHEN_FAILED RAW_VALUE
  5 Reallocated_Sector_Ct   0x0032   100   100   000    Old_age   Always       -       0
  9 Power_On_Hours          0x0032   100   100   000    Old_age   Always       -       21119
 12 Power_Cycle_Count       0x0032   100   100   000    Old_age   Always       -       31
170 Available_Reservd_Space 0x0033   100   100   010    Pre-fail  Always       -       0
171 Program_Fail_Count      0x0032   100   100   000    Old_age   Always       -       0
172 Erase_Fail_Count        0x0032   100   100   000    Old_age   Always       -       0
174 Unsafe_Shutdown_Count   0x0032   100   100   000    Old_age   Always       -       30
175 Power_Loss_Cap_Test     0x0033   100   100   010    Pre-fail  Always       -       8250 (91, 7046)
183 SATA_Downshift_Count    0x0032   100   100   000    Old_age   Always       -       0
184 End-to-End_Error        0x0033   100   100   090    Pre-fail  Always       -       0
187 Reported_Uncorrect      0x0032   100   100   000    Old_age   Always       -       0
190 Temperature_Case        0x0022   075   072   000    Old_age   Always       -       25 (Min/Max 18/28)
192 Unsafe_Shutdown_Count   0x0032   100   100   000    Old_age   Always       -       30
194 Temperature_Internal    0x0022   100   100   000    Old_age   Always       -       25
197 Current_Pending_Sector  0x0012   100   100   000    Old_age   Always       -       0
199 CRC_Error_Count         0x003e   100   100   000    Old_age   Always       -       0
225 Host_Writes_32MiB       0x0032   100   100   000    Old_age   Always       -       3218012
226 Workld_Media_Wear_Indic 0x0032   100   100   000    Old_age   Always       -       1495
227 Workld_Host_Reads_Perc  0x0032   100   100   000    Old_age   Always       -       52
228 Workload_Minutes        0x0032   100   100   000    Old_age   Always       -       1266818
232 Available_Reservd_Space 0x0033   100   100   010    Pre-fail  Always       -       0
233 Media_Wearout_Indicator 0x0032   099   099   000    Old_age   Always       -       0
234 Thermal_Throttle        0x0032   100   100   000    Old_age   Always       -       0/0
241 Host_Writes_32MiB       0x0032   100   100   000    Old_age   Always       -       3218012
242 Host_Reads_32MiB        0x0032   100   100   000    Old_age   Always       -       3537234
243 NAND_Writes_32MiB       0x0032   100   100   000    Old_age   Always       -       8676043

SMART Error Log Version: 1
No Errors Logged

SMART Self-test log structure revision number 1
Num  Test_Description    Status                  Remaining  LifeTime(hours)  LBA_of_first_error
# 1  Short offline       Completed without error       00%         1         -

SMART Selective self-test log data structure revision number 1
 SPAN  MIN_LBA  MAX_LBA  CURRENT_TEST_STATUS
    1        0        0  Not_testing
    2        0        0  Not_testing
    3        0        0  Not_testing
    4        0        0  Not_testing
    5        0        0  Not_testing
Selective self-test flags (0x0):
  After scanning selected spans, do NOT read-scan remainder of disk.
If Selective self-test is pending on power-up, resume after 0 minute delay.

I was informed by TK Support to create an issue here for this kind of requests.

Thank you in advance

**Comment by tniedermeier** [comment]
Hello @ChiyoDraconis,

thank you for your issue report, I just added additional device model numbers, for example your SSDSC2BX800G4, to the existing Intel DC S3610 database entry. Please check out commit 1c811ed. Simply update your local check_smartdb.json file with the new one from the repository.

Best regards,
Thomas
