### ISSUE TITLE
Support for SAS drives

### ISSUE THREAD

**Issue by jcharaoui** [thomas-krenn/check_smart_attributes#61]
SAS drives support SMART but they don't seem to gather the same type of information as ATA drives. Similar to NVme drives, `smartctl` provides a generic output that is the same across different SAS devices.

For example:

```
smartctl 6.6 2016-05-31 r4324 [x86_64-linux-4.18.0-0.bpo.1-amd64] (local build)
Copyright (C) 2002-16, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF INFORMATION SECTION ===
Vendor:               WD
Product:              WD2001FYYG-01SL3
Revision:             VR07
Compliance:           SPC-4
User Capacity:        2 000 398 934 016 bytes [2,00 TB]
Logical block size:   512 bytes
Rotation Rate:        7200 rpm
Form Factor:          3.5 inches
Logical Unit id:      0x50000c0f012173e4
Serial number:        [redacted]
Device type:          disk
Transport protocol:   SAS (SPL-3)
Local Time is:        Mon Oct 29 17:13:12 2018 EDT
SMART support is:     Available - device has SMART capability.
SMART support is:     Enabled
Temperature Warning:  Enabled

=== START OF READ SMART DATA SECTION ===
SMART Health Status: OK

Current Drive Temperature:     27 C
Drive Trip Temperature:        69 C

Manufactured in week 49 of year 2013
Specified cycle count over device lifetime:  1048576
Accumulated start-stop cycles:  32
Specified load-unload count over device lifetime:  1114112
Accumulated load-unload cycles:  68
Elements in grown defect list: 0

Error counter log:
           Errors Corrected by           Total   Correction     Gigabytes    Total
               ECC          rereads/    errors   algorithm      processed    uncorrected
           fast | delayed   rewrites  corrected  invocations   [10^9 bytes]  errors
read:    1435070     1508     16162   1436578       1550     633229,507          42
write:    149385   930373    930375   1079758     930373      62602,780           0
verify:       15        0         0        15          0         50,095           0

Non-medium error count:      840

SMART Self-test log
Num  Test              Status                 segment  LifeTime  LBA_first_err [SK ASC ASQ]
     Description                              number   (hours)
# 1  Background short  Completed                   -   30455                 - [-   -    -]
# 2  Background long   Completed                   -   30441                 - [-   -    -]
# 3  Background short  Completed                   -   30431                 - [-   -    -]
# 4  Background short  Completed                   -   30407                 - [-   -    -]
# 5  Background short  Completed                   -   30383                 - [-   -    -]
# 6  Background short  Completed                   -   30359                 - [-   -    -]

Long (extended) Self Test duration: 15620 seconds [260,3 minutes]
```

The plugin should at least monitor `Total uncorrected errors` (read and write) with warning and critical thresholds at 10 and 20 respectively.

**Comment by tniedermeier** [comment]
Hello @jcharaoui,

thank you so much for your pull request. I'm sorry for my late reply. We will test it with SAS drives soon, probably next week. Would be great if it works smoothly, so we could merge your code.

Best regards,
Thomas

**Comment by tniedermeier** [comment]
Here an output of a SAS drive behind a MegaRAID 9341-4i controller:

tk@x9scmf:~$ sudo smartctl -a -d megaraid,11 /dev/sda
smartctl 6.6 2016-05-31 r4324 [x86_64-linux-4.15.0-50-generic] (local build)
Copyright (C) 2002-16, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF INFORMATION SECTION ===
Vendor:               HITACHI
Product:              HUS156060VLS600
Revision:             A760
Compliance:           SPC-4
User Capacity:        600,127,266,816 bytes [600 GB]
Logical block size:   512 bytes
Rotation Rate:        15030 rpm
Form Factor:          3.5 inches
Logical Unit id:      0x5000cca04117f918
Serial number:        CZVE5R4L
Device type:          disk
Transport protocol:   SAS (SPL-3)
Local Time is:        Wed May 29 14:13:03 2019 UTC
SMART support is:     Available - device has SMART capability.
SMART support is:     Enabled
Temperature Warning:  Enabled

=== START OF READ SMART DATA SECTION ===
SMART Health Status: OK

Current Drive Temperature:     39 C
Drive Trip Temperature:        85 C

Manufactured in week 21 of year 2016
Specified cycle count over device lifetime:  50000
Accumulated start-stop cycles:  3
Elements in grown defect list: 63

Vendor (Seagate) cache information
  Blocks sent to initiator = 5972688896

Error counter log:
           Errors Corrected by           Total   Correction     Gigabytes    Total
               ECC          rereads/    errors   algorithm      processed    uncorrected
           fast | delayed   rewrites  corrected  invocations   [10^9 bytes]  errors
read:          0        1         0         1      13849          0.044           0
write:         0       22         0        22        251          0.001           0
verify:        0        0         0         0      21240          0.000           0

Non-medium error count:        0

No self-tests have been logged

**Comment by tniedermeier** [comment]
Smartctl output looks fine, but if you run the check_smart_attributes command with the following parameter, it states that the drive "megaraid11" is not in the smart database:
sudo ./check_smart_attributes -dbj check_smartdb.json -d megaraid11,/dev/sda
