### ISSUE TITLE
Monitor SMART general health assessment

### ISSUE THREAD

**Issue by jcharaoui** [thomas-krenn/check_smart_attributes#64]
`smartctl` output generally includes a general health self-assessment. When this fails, the drive is predicted to require immediate replacement.

Sample output:
`SMART overall-health self-assessment test result: PASSED`
`SMART Health Status: OK`

It may seem out of scope for this plugin which monitors specific SMART *attributes* but consider:
* It could provide a valuable fail-safe in case thresholds are too high
* It's possible SMART firmware may decide to fail a device even though monitored attributes are within tolerance (unfortunately SMART is somewhat of a black-box)
* The plugin could fallback to this status information when a drive is absent from `smartdb.json`

**Comment by tniedermeier** [comment]
Hello @jcharaoui,

thank you for your great idea and sorry for the huge delay of my response.
We'll keep this feature in mind and try to implement it in the next couple of weeks.
We'll keep you informed.

Best regards,
Thomas

**Comment by gschoenberger** [comment]
We are now checking "SMART overall-health self-assessment test result: PASSED" in the plugin.
I will open a new issue for "SMART Health Status: OK" as this status is not present at all devices (SSDs, NVMe).
Checking "SMART overall-health self-assessment test result: PASSED" is done by commits:
- 31d55e9c9cb56ff9d31728b92a8c4cbdd2254f0c
- dbd44b30053fe112b880fb1fb5240177f57e5e51
