### ISSUE TITLE
Possible to monitor multiple megaraid devices?

### ISSUE THREAD

**Issue by HHawk** [thomas-krenn/check_smart_attributes#66]
First off; excellent plugin! Still "fooling" around with it and trying to get used to it. But it has great potential.

The only thing I am "missing" is a way to monitor all available drives.
For example; I have a PowerEdge R610 with a PERC H700 RAID controller (Symbios Logic MegaRAID SAS 2108). Therefor I have to use the "megaraid" command (sidenote: storcli doesn't show any controllers).

After fooling around a bit I noticed the following command works:
`sudo ./check_smart_attributes -dbj check_smartdb.json -d megaraid1,/dev/sda -O 'sat+'`

Which outputs:
`OK (megaraid1) |'megaraid1_Airflow_Temperature_Cel'=26;50;60 'megaraid1_Temperature_Celsius'=26;50;60 'megaraid1_Available_Reservd_Space'=100;16;11 'megaraid1_Media_Wearout_Indicator'=100;16;6 'megaraid1_Total_LBAs_Written'=3014 'megaraid1_Total_LBAs_Read'=17679`

The command: 
`sudo ./check_smart_attributes -dbj check_smartdb.json -d megaraid1,/dev/sda -vvv`

Did not work for me, result: Error: the following device(s) where not found in the smartdb JSON file: /dev/megaraid1

So, so far it works as expected with the first command (described above).

However I was wondering if it's possible to run SMART checks on all available disks in the RAID array? I tried using the following command (which I found somewhere in a different post):

`sudo ./check_smart_attributes -dbj check_smartdb.json -d megaraid[0-5]$,/dev/sda -O 'sat+'`

But that did not work. As a result I received: Error: the following device(s) where not found in the smartdb JSON file: megaraid[0-5]$,/dev/sda

Did I do something wrong? Would be great if it checked all available drives on their SMART attributes automatically without having to enter something like:

```
sudo ./check_smart_attributes -dbj check_smartdb.json -d megaraid1,/dev/sda -O 'sat+'
sudo ./check_smart_attributes -dbj check_smartdb.json -d megaraid2,/dev/sda -O 'sat+'
sudo ./check_smart_attributes -dbj check_smartdb.json -d megaraid3,/dev/sda -O 'sat+'
```
Because creating various different rules / commands for every server I have, is a lot of work. So if it does this automatically it would be great. Maybe this is possible and I overlooked it?

Thanks a million in advance!

Regards

**Comment by gschoenberger** [comment]
Can you also post the plugin output with "-vvv"?

**Comment by gschoenberger** [comment]
And can you als post the output of:
`find /dev -regextype egrep -regex megaraid[0-5] -type f,l,b`

**Comment by gschoenberger** [comment]
You did nothing wrong, THX for the command outputs.
I've talked to @tk-wfischer and currently there is no straight way to get all megaraid devices and their corresponding /dev/sd* devices automatically. (unless completely integrating calls to storcli)
That means, that unfortunately you have to manually find out your megaraid devices (with storcli) and match them to /dev/sd* devices for configuring the plugin.

If you have system without raid controllers you can simply use a regular expression to check all devices (but this is not possible with devices hidden by the raid controller):
```
# ./check_smart_attributes -dbj ./check_smartdb.json -r '.*sd[c-f]'
OK (sdf, sdc, sde, sdd)

```

**Comment by HHawk** [comment]
Ow.... :'(

I only have systems with RAID configurations unfortunately. So I won't be able to use this.
The command storecli doesn't work. It shows 0 controllers.

I was hoping this was possible, especially with multiple RAID cards (LSI, HP, etc.).

Will this functionality be added in the (near) future? Or not at all?

Thank you nevertheless so far for your time though.

Regards

**Comment by tniedermeier** [comment]
Hello,

you wrote in your initial post that you're utilizing a DELL PERC H700 RAID controller. Please use in this case the perccli tool instead of standard storcli. We already discussed this issue here: https://github.com/thomas-krenn/check_lsi_raid/issues/26
Here also a support page from DELL regarding perccli: https://www.dell.com/support/article/at/de/atbsdt1/sln283135/how-to-use-the-poweredge-raid-controller-perc-command-line-interface-cli-utility-to-manage-your-raid-controller?lang=en

Best regards,
Thomas

**Comment by HHawk** [comment]
Sorry, I did search, but I didn't find that thread.

I installed it and ran the command: sudo perccli64 /c0 /eall/sall show
It gives the following output:
```
Controller = 0
Status = Success
Description = Show Drive Information Succeeded.

Drive Information :
=================

----------------------------------------------------------------------------
EID:Slt DID State DG       Size Intf Med SED PI SeSz Model               Sp
----------------------------------------------------------------------------
0:0       2 Onln   0 446.625 GB SATA SSD N   N  512B INTEL SSDSC2KG480G8 U
0:1       1 Onln   0 446.625 GB SATA SSD N   N  512B INTEL SSDSC2KG480G8 U
0:2       3 Onln   0 446.625 GB SATA SSD N   N  512B INTEL SSDSC2KG480G8 U
----------------------------------------------------------------------------

EID-Enclosure Device ID|Slt-Slot No.|DID-Device ID|DG-DriveGroup
DHS-Dedicated Hot Spare|UGood-Unconfigured Good|GHS-Global Hotspare
UBad-Unconfigured Bad|Onln-Online|Offln-Offline|Intf-Interface
Med-Media Type|SED-Self Encryptive Drive|PI-Protection Info
SeSz-Sector Size|Sp-Spun|U-Up|D-Down/PowerSave|T-Transition|F-Foreign
UGUnsp-Unsupported|UGShld-UnConfigured shielded|HSPShld-Hotspare shielded
CFShld-Configured shielded|Cpybck-CopyBack|CBShld-Copyback Shielded
```

But I don't understand how that helps to be used in "regular expression", because isn't this the same as before when I used:
```
sudo ./check_smart_attributes -dbj check_smartdb.json -d megaraid1,/dev/sda
sudo ./check_smart_attributes -dbj check_smartdb.json -d megaraid2,/dev/sda
sudo ./check_smart_attributes -dbj check_smartdb.json -d megaraid3,/dev/sda
```

Maybe I am mistaken and this is completely different? I doubt it as I have the same result as before. I already succesfully got the SMART status from each SSD behind RAID manually, but I want them in one command obviously (regex?).

Regards

**Comment by gschoenberger** [comment]
**You cannot use the regular expression feature with raid controllers!**
So this will not work for you:
> But I don't understand how that helps to be used in "regular expression", because isn't this the same as before when I used:

All you can do now is to set up the checks manually for each device...

**Comment by HHawk** [comment]
Sad news... 

I know there is different plugin called "check_smart v2" [here](https://www.claudiokuenzler.com/monitoring-plugins/check_smart.php), however I liked the idea you could add HDD's, SSD's, etc. to the json file with "check_smart_attributes". Which is better imho and also more user friendly.

Will the regex feature be updated / more useful in the near future. Or is this a definite no go?

Maybe it's worth the time to investigate the regex function of "check_smart v2" and combine the best of two worlds? With "check_smart v2" it is possible to use regex with RAID controllers.

Anyways, thank you all for answering. I hope to see some updates in the near future.

Regards

**Comment by gschoenberger** [comment]
Can you test the latest plugin version with commit 564031410395282bf0ddabc3fb1f546e7fa84df5?
Call:
`sudo ./check_smart_attributes -dbj check_smartdb.json -d megaraid[0-3],/dev/sda -O 'sat+'`
to check from megaraid0 to megaraid3 with corresponding /dev/sda.
Note that AFAIK you cannot use e.g. megaraid3 with /dev/sda if megaraid3 belongs to /dev/sdb on raid controller side...

**Comment by HHawk** [comment]
Wow!!! It works! So far so good. Thank you gschoenberger!

[root]#  sudo ./check_smart_attributes -dbj check_smartdb.json -r 'megaraid[1-3],/dev/sda' -O 'sat+'
Gives:
`OK (megaraid3, megaraid1, megaraid2) |'megaraid3_Airflow_Temperature_Cel'=26;50;60 'megaraid3_Temperature_Celsius'=26;50;60 'megaraid3_Available_Reservd_Space'=100;16;11 'megaraid3_Media_Wearout_Indicator'=100;16;6 'megaraid3_Total_LBAs_Written'=4356 'megaraid3_Total_LBAs_Read'=18417 'megaraid1_Airflow_Temperature_Cel'=27;50;60 'megaraid1_Temperature_Celsius'=27;50;60 'megaraid1_Available_Reservd_Space'=100;16;11 'megaraid1_Media_Wearout_Indicator'=100;16;6 'megaraid1_Total_LBAs_Written'=4358 'megaraid1_Total_LBAs_Read'=18417 'megaraid2_Airflow_Temperature_Cel'=26;50;60 'megaraid2_Temperature_Celsius'=26;50;60 'megaraid2_Available_Reservd_Space'=100;16;11 'megaraid2_Media_Wearout_Indicator'=100;16;6 'megaraid2_Total_LBAs_Written'=4353 'megaraid2_Total_LBAs_Read'=18418`

So this update works!


I do have one question. I really have no clue if it's fixable? If I run the command like this:
`sudo ./check_smart_attributes -dbj check_smartdb.json -r 'megaraid[0-8],/dev/sda' -O 'sat+'`

It will output:
`Error: smartctl returned "No such device" for device /dev/megaraid0.`

Similar result with, for example, when using [1-8].

Instead of putting out an error, is it possible to make it work so, that it just skips "No such device" in general? So I can use this command to check several server's disk's SMART status at one time, instead of configuring each seperately. Sorry for asking.

I really appreciate your help! Especially considering this plugin is better than the other one. Especially since you add SSD's, HDD's, etc. for SMART.

Once again; THANK YOU! :-)

Regards

**Comment by gschoenberger** [comment]
There is due to the fact that your disk is not in the smartdb.json file. The simplest fix would be to add all your disks to our smartdb, as without it smart monitoring is not possible.

Currently we have no option to skip not found devices...

**Comment by HHawk** [comment]
I don't think this is related to the drive not being in the check_smartdb.json file.
Actually it is in the smartdb.json file: 

```
"Intel DC S4600, D3-S4610, D3-S4510" : {
"Device" : ["Intel DC S4600 Series SSDs","Intel D3-S4610 Series SSDs","Intel D3-S4510 Series SSDs","INTEL SSDSC2KG240G701","INTEL SSDSC2KG480G701","INTEL SSDSC2KG960G701","INTEL SSDSC2KG019T701","INTEL SSDSC2KG240G801","INTEL SSDSC2KG480G801","INTEL SSDSC2KG960G801","INTEL SSDSC2KG019T801","INTEL SSDSC2KG038T801","INTEL SSDSC2KB240G8","INTEL SSDSC2KB480G8","INTEL SSDSC2KB960G8","INTEL SSDSC2KB019T8","INTEL SSDSC2KB038T8","INTEL SSDSC2KG480G8"],
```

SMART output:
`Device Model:     INTEL SSDSC2KG480G8`

I even added "INTEL SSDSC2KG480G8" manually as there were only models in there with "01" added to the drive. 

I think the issue is that the devices do not exists, hence why I posted my previous message.

But I simply solved it myself by commenting the part which is responsible for the "No such device" message:

```
                #if(($? >> 8) & 2){
                #       print "Error: smartctl returned \"No such device\" for device $device.\n";
                #       exit(STATE_UNKNOWN);
                #}
```

and:

```
        #if(@$devices_missing_a){
        #       print "Error: the following device(s) where not found in the smartdb JSON file: ";
        #       print printMissingDevicesDB($devices_missing_a)."\n";
        #       if(!defined($criticalOnUnknown)){
        #               exit(STATE_UNKNOWN);
        #       }
        #       else {
        #               exit(STATE_CRITICAL);
        #       }
        #}
```


Seems to work now as expected?
Command: 
`sudo ./check_smart_attributes -dbj check_smartdb.json -r 'megaraid[0-9],/dev/sda' -O 'sat+'`

Output:
```
sudo ./check_smart_attributes -dbj check_smartdb.json -r 'megaraid[0-9],/dev/sda' -O 'sat+'
OK (megaraid3, megaraid2, megaraid1) |'megaraid3_Airflow_Temperature_Cel'=25;50;60 'megaraid3_Temperature_Celsius'=25;50;60 'megaraid3_Available_Reservd_Space'=100;16;11 'megaraid3_Media_Wearout_Indicator'=100;16;6 'megaraid3_Total_LBAs_Written'=4638 'megaraid3_Total_LBAs_Read'=18446 'megaraid2_Airflow_Temperature_Cel'=25;50;60 'megaraid2_Temperature_Celsius'=25;50;60 'megaraid2_Available_Reservd_Space'=100;16;11 'megaraid2_Media_Wearout_Indicator'=100;16;6 'megaraid2_Total_LBAs_Written'=4634 'megaraid2_Total_LBAs_Read'=18448 'megaraid1_Airflow_Temperature_Cel'=26;50;60 'megaraid1_Temperature_Celsius'=26;50;60 'megaraid1_Available_Reservd_Space'=100;16;11 'megaraid1_Media_Wearout_Indicator'=100;16;6 'megaraid1_Total_LBAs_Written'=4640 'megaraid1_Total_LBAs_Read'=18446
```

Obviously not the best solution, but at least it checks all possible devices / disks this way. The only thing I need to make sure of, is that they are in the check_smartdb.json ofcourse. So maybe I will add to versions of the script; one for testing which shows "No such device" and one which I use for Nagios.

**Comment by gschoenberger** [comment]
I am closing this issue now, if still desired we can open an new issue for skipping not found devices...
