### ISSUE TITLE
Check smart attributes for X400s and X600s

### ISSUE THREAD

**Issue by gschoenberger** [thomas-krenn/check_smart_attributes#78]
I think we must re-check the smart thresholds introduced by commit:
97271f9c37a03540467674888a05cb5d565d218b

@tniedermeier @tk-wfischer Can you help with that?

**Comment by tniedermeier** [comment]
I requested the SMART attributes and values from SanDisk and updated both entries, please take a look at my commit: a366d3d571d510366b94fc3f555fb8840f730a80
@gschoenberger Please take a look

**Comment by gschoenberger** [comment]
184 is "End to End Error Data Detection", but no "Thresh" is defined.
Is this correct or should we define thresholds and check the value?

**Comment by tniedermeier** [comment]
There is no threshold defined in the specification of these drives, I checked the SMART specification once again.

**Comment by gschoenberger** [comment]
Fixed by commit 3a1488338da2b80bee45e6b6a570c7bd7308b4f0
