### ISSUE TITLE
Help adding a new Model

### ISSUE THREAD

**Issue by Melkor333** [thomas-krenn/check_smart_attributes#84]
I have multiple [Seagate Exos X16](https://www.seagate.com/de/de/support/internal-hard-drives/enterprise-hard-drives/exos-X16/) disks, which have the model number `ST14000NM001G-2KJ103`.
I thought I might be able to add this model number to the existing Device Type ` Seagate Exos X`, but when I test it on my machine, it only shows me the temperature. Is this correct?:
```
root@host:~# /usr/lib/nagios/plugins/check_smart_attributes -dbj /usr/lib/nagios/plugins/check_smartdbi_local.json -d /dev/sda
OK (sda) |'sda_Temperature_Celsius'=30;54;60
```
In contrast, the nvme disks show a lot more informations:
```
root@host:~# /usr/lib/nagios/plugins/check_smart_attributes -dbj /usr/lib/nagios/plugins/check_smartdbi_local.json -d /dev/nvme0
OK (nvme0) |'Temperature'=43;50;60 'Available Spare'=100;16;11 'Percentage Used'=0;85;90 'Data Units Read'=8284.488192 'Data Units Written'=8043.582976 'Host Read Commands'=125713164 'Host Write Commands'=122775044 'Power Cycles'=7 'Power On Hours'=510
```

This is the smartctl output for the Seagate disk:
```
root@px18m:~# smartctl -a /dev/sda
smartctl 7.0 2018-12-30 r4883 [x86_64-linux-5.3.10-1-pve] (local build)
Copyright (C) 2002-18, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF INFORMATION SECTION ===
Device Model:     ST14000NM001G-2KJ103
Serial Number:    ZL207TB8
LU WWN Device Id: 5 000c50 0b66a8dd8
Firmware Version: SN02
User Capacity:    14,000,519,643,136 bytes [14.0 TB]
Sector Sizes:     512 bytes logical, 4096 bytes physical
Rotation Rate:    7200 rpm
Form Factor:      3.5 inches
Device is:        Not in smartctl database [for details use: -P showall]
ATA Version is:   ACS-4 (minor revision not indicated)
SATA Version is:  SATA 3.3, 6.0 Gb/s (current: 6.0 Gb/s)
Local Time is:    Thu Feb  6 16:13:12 2020 CET
SMART support is: Available - device has SMART capability.
SMART support is: Enabled

=== START OF READ SMART DATA SECTION ===
SMART overall-health self-assessment test result: PASSED

General SMART Values:
Offline data collection status:  (0x82) Offline data collection activity
                                        was completed without error.
                                        Auto Offline Data Collection: Enabled.
Self-test execution status:      (   0) The previous self-test routine completed
                                        without error or no self-test has ever
                                        been run.
Total time to complete Offline
data collection:                (  567) seconds.
Offline data collection
capabilities:                    (0x7b) SMART execute Offline immediate.
                                        Auto Offline data collection on/off support.
                                        Suspend Offline collection upon new
                                        command.
                                        Offline surface scan supported.
                                        Self-test supported.
                                        Conveyance Self-test supported.
                                        Selective Self-test supported.
SMART capabilities:            (0x0003) Saves SMART data before entering
                                        power-saving mode.
                                        Supports SMART auto save timer.
Error logging capability:        (0x01) Error logging supported.
                                        General Purpose Logging supported.
Short self-test routine
recommended polling time:        (   1) minutes.
Extended self-test routine
recommended polling time:        (1300) minutes.
Conveyance self-test routine
recommended polling time:        (   2) minutes.
SCT capabilities:              (0x70bd) SCT Status supported.
                                        SCT Error Recovery Control supported.
                                        SCT Feature Control supported.
                                        SCT Data Table supported.

SMART Attributes Data Structure revision number: 10
Vendor Specific SMART Attributes with Thresholds:
ID# ATTRIBUTE_NAME          FLAG     VALUE WORST THRESH TYPE      UPDATED  WHEN_FAILED RAW_VALUE
  1 Raw_Read_Error_Rate     0x000f   083   066   044    Pre-fail  Always       -       190666661
  3 Spin_Up_Time            0x0003   095   095   000    Pre-fail  Always       -       0
  4 Start_Stop_Count        0x0032   100   100   020    Old_age   Always       -       5
  5 Reallocated_Sector_Ct   0x0033   100   100   010    Pre-fail  Always       -       0
  7 Seek_Error_Rate         0x000f   078   061   045    Pre-fail  Always       -       64112657
  9 Power_On_Hours          0x0032   100   100   000    Old_age   Always       -       502
 10 Spin_Retry_Count        0x0013   100   100   097    Pre-fail  Always       -       0
 12 Power_Cycle_Count       0x0032   100   100   020    Old_age   Always       -       5
 18 Unknown_Attribute       0x000b   100   100   050    Pre-fail  Always       -       0
187 Reported_Uncorrect      0x0032   100   100   000    Old_age   Always       -       0
188 Command_Timeout         0x0032   100   100   000    Old_age   Always       -       0
190 Airflow_Temperature_Cel 0x0022   069   049   040    Old_age   Always       -       31 (Min/Max 29/31)
192 Power-Off_Retract_Count 0x0032   100   100   000    Old_age   Always       -       1
193 Load_Cycle_Count        0x0032   100   100   000    Old_age   Always       -       32
194 Temperature_Celsius     0x0022   031   040   000    Old_age   Always       -       31 (0 24 0 0 0)
197 Current_Pending_Sector  0x0012   100   100   000    Old_age   Always       -       0
198 Offline_Uncorrectable   0x0010   100   100   000    Old_age   Offline      -       0
199 UDMA_CRC_Error_Count    0x003e   200   200   000    Old_age   Always       -       0
200 Multi_Zone_Error_Rate   0x0023   100   100   001    Pre-fail  Always       -       0
240 Head_Flying_Hours       0x0000   100   253   000    Old_age   Offline      -       243 (157 109 0)
241 Total_LBAs_Written      0x0000   100   253   000    Old_age   Offline      -       109538325072
242 Total_LBAs_Read         0x0000   100   253   000    Old_age   Offline      -       109508606873

SMART Error Log Version: 1
No Errors Logged

SMART Self-test log structure revision number 1
No self-tests have been logged.  [To run self-tests, use: smartctl -t]

SMART Selective self-test log data structure revision number 1
 SPAN  MIN_LBA  MAX_LBA  CURRENT_TEST_STATUS
    1        0        0  Not_testing
    2        0        0  Not_testing
    3        0        0  Not_testing
    4        0        0  Not_testing
    5        0        0  Not_testing
Selective self-test flags (0x0):
  After scanning selected spans, do NOT read-scan remainder of disk.
If Selective self-test is pending on power-up, resume after 0 minute delay.
```

I also wonder how to get the proper infos for new disks.
I assume that you take the information of the `smartctl`, but how do you define the Thresholds (I see only one value in the smartctl output) and `Perfs`?
Would be great if you could add a short explanation to the README on how to get the proper information to create a correct JSON for new disks. 🙂

**Comment by gschoenberger** [comment]
Hi! THX for your request. To clarify on how to add a new disk:
1. The drive should be in the smartmontools database, because then you can rely on the output of smartctl -> check the information section of "smartctl -a" for "Device is:"

2. Next add the new device to the check_smartdb.json file
- The "Device" key of the JSON entry has to match the "Device Model" of the smartctl output -> this is how the plugin (check_smartdb.json) and smartmontools (smartctl) are connected.
- The "ID#" defines which value of smartctl ("VALUE" or "RAW_VALUE") has to be checked by the plugin. As the plugin was initially made for SSDs this is the key step to get a proper monitoring. Each SSD has it's own SMART specification therefore one must check the specification to get to know if "VALUE" or "RAW_VALUE" is relevant. To sum it up -> without SMART spec it is not possible to form a correct entry in the smartdb.json file of the plugin.

3. After adding the device and checking the corresponding SMART specification, define in the check_smartdb.json file which attributes to monitor 
- The "Threshs" key of the JSON entry defines which attributes to monitor. "Threshs" defines thresholds for the values ("VALUE" or "RAW_VALUE") defined by the corresponding "ID#" entry.
Let's take an example: 
The following entry says:
    * For smart attribute "1" of smartctl take into account: VALUE
    * For smart attribute "3" of smartctl take into account: VALUE
    * For smart attribute "4" of smartctl take into account: RAW_VALUE
    * For smart attribute "194" of smartctl take into account: RAW_VALUE
```
    		"Seagate Exos X" : {
			"Device" : ["Seagate Exos X","ST10000NM0156"],
			"ID#" : {
				"1" : "VALUE", # Raw Read Error Rate
				"3" : "VALUE", # Spin Up Time
				"4" : "RAW_VALUE", # Start Stop Count
                                "5" : "RAW_VALUE", # Re-allocated Sector Count
                                "194" : "RAW_VALUE", # Temperature Celsius
```
- And the corresponding thresholds:
    * For smart attribute "1" of smartctl, if VALUE (see "ID#" above) is smaller than 62 -> WARNING, if smaller than 52 -> CRITICAL
    * For smart attribute "3" of smartctl, if VALUE (see "ID#" above) is smaller than 32 -> WARNING, if smaller than 22 -> CRITICAL
    * For smart attribute "5" of smartctl, if RAW_VALUE (see "ID#" above) is greater than 20 -> WARNING, if greater than 40 -> CRITICAL
    * For smart attribute "194" of smartctl, if RAW_VALUE (see "ID#" above) is greater than 54 -> WARNING, if greater than 60 -> CRITICAL
```
			"Threshs" : {
				"1" : ["62:","52:"],
				"3" : ["32:","22:"],
				"5" : ["20","40"],
                                "194" : ["54","60"],
```
**IMPORTANT**: As there is no "Threshs" entry for attribute number "4" -> this attribute will not be monitored by the plugin!

4.  Define in the check_smartdb.json file which attributes should be printed as performance data
- The "Perfs" key of the JSON entry defines which attributes to print as performance data.
Let's take an example: 
The following entry says:
    * For smart attribute "194" print "RAW_VALUE" as performance data (see "ID#" above)
```
                             "Perfs" : ["194"]
```

Back to your question: do you now know which values are checked and which value(s) are printed as performance data for your Exos disk?

**Comment by gschoenberger** [comment]
Added to README with commit 2af12b8833801a5192f6746cb581b161ce493376

**Comment by Melkor333** [comment]
Thank you a lot for your very in depth answer and also for the extension of the README file!

I'm sorry I didn't respond to you earlier. I have opened a ticket on the smartmondb tracker to get the disk into the database. After that I will create a PR to add the device to the JSON file. :)
