### ISSUE TITLE
SMART Status on LSI MegaRAID Error

### ISSUE THREAD

**Issue by vlar** [thomas-krenn/check_smart_attributes#86]
Hello, 

I'm currently facing an issue with your plugin which works perfectly on our others RAID platforms but for the megaraid. here is the issue: 

`/usr/local/nagios/libexec/check_smart_attributes -dbj /etc/nagios-plugins/config/check_smartdb.json  -d megaraid4,/dev/sda1`

Returns: 

Error: the following device(s) were not found in the smartdb JSON file: megaraid4,/dev/sda1

`storcli /c0 /eall/sall show`

Returns: 

```
----------------------------------------------------------------------------
EID:Slt DID State DG       Size Intf Med SED PI SeSz Model               Sp 
----------------------------------------------------------------------------
252:0     7 Onln   0 744.687 GB SATA SSD N   N  512B INTEL SSDSC2BB800H4 U  
252:1     4 Onln   0 744.687 GB SATA SSD N   N  512B INTEL SSDSC2BB800H4 U  
252:2     6 Onln   0 744.687 GB SATA SSD N   N  512B INTEL SSDSC2BB800H4 U  
252:3     5 Onln   0  893.75 GB SATA SSD N   N  512B INTEL SSDSC2KB960G8 U  
----------------------------------------------------------------------------
```

```
fdsik -l

   Device Boot      Start         End      Blocks   Id  System
/dev/sda1               1      194426  1561722879+  ee  GPT
```

And smartmon tools returns this which I suspect is the cause of the error and I'm not sure how to solve it : 

smartctl -a -d megaraid,4  /dev/sda1

```
smartctl 5.43 2016-09-28 r4347 [x86_64-linux-2.6.32-042stab113.17] (local build)
Copyright (C) 2002-12 by Bruce Allen, http://smartmontools.sourceforge.net

/dev/sda1 [megaraid_disk_04] [SAT]: Device open changed type from 'megaraid' to 'sat'
Smartctl open device: /dev/sda1 [megaraid_disk_04] [SAT] failed: SATA device detected,
MegaRAID SAT layer is reportedly buggy, use '-d sat+megaraid,N' to try anyhow
```

Which works : 

```
smartctl -a -d sat+megaraid,4

 /dev/sda1smartctl 5.43 2016-09-28 r4347 [x86_64-linux-2.6.32-042stab113.17] (local build)
Copyright (C) 2002-12 by Bruce Allen, http://smartmontools.sourceforge.net

/dev/sda1 [megaraid_disk_04] [SAT]: Device open changed type from 'megaraid' to 'sat'
Smartctl open device: /dev/sda1 [megaraid_disk_04] [SAT] failed: SATA device detected,
MegaRAID SAT layer is reportedly buggy, use '-d sat+megaraid,N' to try anyhow
[root@linvpsnode10 check_smart_attributes-master]# smartctl -a -d sat+megaraid,4  /dev/sda1
smartctl 5.43 2016-09-28 r4347 [x86_64-linux-2.6.32-042stab113.17] (local build)
Copyright (C) 2002-12 by Bruce Allen, http://smartmontools.sourceforge.net

=== START OF INFORMATION SECTION ===
Device Model:     INTEL SSDSC2BB800H4
Serial Number:    BTWH447402DN800CGN
```

How to make this work with the Nagios Plugins ?

**Comment by gschoenberger** [comment]
Hi!
Have you tried to add the "sat+" via "-O"?
`/usr/local/nagios/libexec/check_smart_attributes -dbj /etc/nagios-plugins/config/check_smartdb.json -d megaraid4,/dev/sda1 -O 'sat+'`

"-O" can be used together with megaraid devices (line 303ff):
```
if(defined($extraOpts)){
	if($extraOpts ne 'sat+'){
		print "Error: please use 'sat+' as extra options for megaraid devices!\n";
		print getUsageString();
		exit(STATE_UNKNOWN);
	}
	$megaDeviceOptions = $extraOpts.$megaDevice
}
```

**Comment by vlar** [comment]
I just tried it as I hadn't before it seems to returns the same error:  

`/usr/local/nagios/libexec/check_smart_attributes -dbj /etc/nagios-plugins/config/check_smartdb.json -d megaraid4,/dev/sda1 -O 'sat+'
Error: the following device(s) were not found in the smartdb JSON file: megaraid4,/dev/sda1`

**Comment by gschoenberger** [comment]
Can you post the verbose output with -vvv? Then we could inspect the smartctl command

**Comment by vlar** [comment]
Unless I do it wrong there is no further output with the verbose mode: 


```
/usr/local/nagios/libexec/check_smart_attributes -vvv -dbj /etc/nagios-plugins/config/check_smartdb.json -d megaraid6,/dev/sda -O 'sat+'
Error: the following device(s) were not found in the smartdb JSON file: megaraid6,/dev/sda]
```

Some more Smart CTL output in case it would help. 

`smartctl -a -d sat+megaraid,6  /dev/sda1
smartctl 5.43 2016-09-28 r4347 [x86_64-linux-2.6.32-042stab113.17] (local build)
Copyright (C) 2002-12 by Bruce Allen, http://smartmontools.sourceforge.net

=== START OF INFORMATION SECTION ===
Device Model:     INTEL SSDSC2BB800H4
Serial Number:    BTWH447404UD800CGN
LU WWN Device Id: 5 5cd2e4 04b725d49
Firmware Version: D2010380
User Capacity:    800,166,076,416 bytes [800 GB]
Sector Sizes:     512 bytes logical, 4096 bytes physical
Device is:        Not in smartctl database [for details use: -P showall]
ATA Version is:   8
ATA Standard is:  ACS-2 revision 3
Local Time is:    Tue May 26 10:52:21 2020 CEST
SMART support is: Available - device has SMART capability.
SMART support is: Enabled`

**Comment by gschoenberger** [comment]
And you are sure the device is in your check_smartdb.json?
-> SSDSC2BB800H4 must be as device in the smartdb.json file...

**Comment by vlar** [comment]
Oh i didn't figure that far: 

`cat /etc/nagios-plugins/config/check_smartdb.json | grep SSDSC2BB800H4`

Is empty. 

I'll refer to the check_smartdb.json part of the wiki. I just went through it

**Comment by gschoenberger** [comment]
As it is a "Intel DC S3500"  I can add it to the other 3500s. OK?

**Comment by vlar** [comment]
That would indeed be fine for what I have grasped of the logic. 

That would mean I would need to download back the /check_smartdb.json, right?

**Comment by gschoenberger** [comment]
I have added SSDSC2BB800H4 to the smartdb.
Yes you have to download the new version and also ensure to use the latest plugin as the format of the smartdb JSON file has changed (is now valid JSON).

**Comment by vlar** [comment]
Thank you for your update. I have updated the plugin but the issue persists but here I suspect I must do something wrong: 

`cat /etc/nagios-plugins/config/check_smartdb.json | grep SSDSC2BB800H4
                        "Device" : ["Intel DC S3500 Series SSDs","INTEL SSDSC2BB080G4","INTEL SSDSC2BB120G4","INTEL SSDSC2BB160G4","INTEL SSDSC2BB240G4","INTEL SSDSC2BB
300G4","INTEL SSDSC2BB480G4","INTEL SSDSC2BB600G4","INTEL SSDSC2BB800G4","INTEL SSDSC2BB800H4","INTEL SSDSC2BB012T4","INTEL SSDSC2BB150G7"],`

```
/usr/local/nagios/libexec/check_smart_attributes -vvv -dbj /etc/nagios-plugins/config/check_smartdb.json -d megaraid6
,/dev/sda1 -O 'sat+'
Error: the following device(s) were not found in the smartdb JSON file: megaraid6,/dev/sda1
```

**Comment by tniedermeier** [comment]
Hi guys,

@gschoenberger told me to test the current version of the plugin also, in my case a Proxmox VE with a MegaRAID 9460-8i Controller and a Intel SSDSC2BB080G4 SSD.

Smartctl output is fine, I think and it states that the device is in the database:

```
root@pve:~/check_smart_attributes# smartctl -a -d megaraid,0 /dev/sda
smartctl 7.1 2019-12-30 r5022 [x86_64-linux-5.4.44-1-pve] (local build)
Copyright (C) 2002-19, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF INFORMATION SECTION ===
Model Family:     Intel 730 and DC S35x0/3610/3700 Series SSDs
Device Model:     INTEL SSDSC2BB080G4
Serial Number:    BTWL326004NP080KGN
LU WWN Device Id: 5 001517 8f365454e
Firmware Version: D2010355
User Capacity:    80,026,361,856 bytes [80.0 GB]
Sector Size:      512 bytes logical/physical
Rotation Rate:    Solid State Device
Form Factor:      2.5 inches
Device is:        In smartctl database [for details use: -P show]
ATA Version is:   ATA8-ACS T13/1699-D revision 4
SATA Version is:  SATA 2.6, 6.0 Gb/s (current: 6.0 Gb/s)
Local Time is:    Thu Jun 18 15:19:31 2020 CEST
SMART support is: Available - device has SMART capability.
SMART support is: Enabled
[...]
```

Plugin Output:

```
root@pve:~/check_smart_attributes# ./check_smart_attributes -d megaraid0,/dev/sda -dbj check_smartdb.json
Error: the following device(s) were not found in the smartdb JSON file: megaraid0,/dev/sda
```

Plugin output with the option -O:

```
root@pve:~/check_smart_attributes# ./check_smart_attributes -d megaraid0,/dev/sda -dbj check_smartdb.json -O 'sat+'
Error: the following device(s) were not found in the smartdb JSON file: megaraid0,/dev/sda
```

**Comment by tniedermeier** [comment]
I think @gschoenberger found the solution ;-)

```
root@pve:~/check_smart_attributes# ./check_smart_attributes -d megaraid0,/dev/sda -dbj check_smartdb.json -O 'sat+'
Warning (megaraid0) [megaraid0_ATA_Error_Count = Warning]|'megaraid0_Temperature_Case'=25;50;60 'megaraid0_Temperature_Internal'=25;50;60 'megaraid0_Available_Reservd_Space'=100;16;11 'megaraid0_Media_Wearout_Indicator'=085;16;6 'megaraid0_Host_Writes_32MiB'=967316 'megaraid0_Host_Reads_32MiB'=2874619
```

**Comment by vlar** [comment]
I just tried your command and it doesn't work for me but if i don't add the sat+ statement in smartctl it won't work unlike your config. 

`smartctl -a -d megaraid,5 /dev/sda1
smartctl 5.43 2016-09-28 r4347 [x86_64-linux-2.6.32-042stab113.17] (local build)
Copyright (C) 2002-12 by Bruce Allen, http://smartmontools.sourceforge.net

/dev/sda1 [megaraid_disk_05] [SAT]: Device open changed type from 'megaraid' to 'sat'
Smartctl open device: /dev/sda1 [megaraid_disk_05] [SAT] failed: SATA device detected,
MegaRAID SAT layer is reportedly buggy, use '-d sat+megaraid,N' to try anyhow`


```
smartctl -a -d sat+megaraid,5 /dev/sda1
smartctl 5.43 2016-09-28 r4347 [x86_64-linux-2.6.32-042stab113.17] (local build)
Copyright (C) 2002-12 by Bruce Allen, http://smartmontools.sourceforge.net

=== START OF INFORMATION SECTION ===
Device Model:     INTEL SSDSC2BB800H4
Serial Number:    BTWH447402DN800CGN
LU WWN Device Id: 5 5cd2e4 04b725259
Firmware Version: D2010380
User Capacity:    800,166,076,416 bytes [800 GB]
Sector Sizes:     512 bytes logical, 4096 bytes physical
Device is:        Not in smartctl database [for details use: -P showall]
ATA Version is:   8
ATA Standard is:  ACS-2 revision 3
Local Time is:    Fri Jun 26 10:52:27 2020 CEST
SMART support is: Available - device has SMART capability.
SMART support is: Enabled
```

And then running your command: 

`usr/local/nagios/libexec/check_smart_attributes  -d megaraid5,/dev/sda1 -dbj /etc/nagios-plugins/config/check_smartdb.json -O 'sat+'
Error: the following device(s) were not found in the smartdb JSON file: megaraid5,/dev/sda1`

**Comment by gschoenberger** [comment]
Can you try to use /dev/sda instead of /dev/sda1?

**Comment by vlar** [comment]
I had tried just in case but it didn't work. 
I just run the command again : 

`/usr/local/nagios/libexec/check_smart_attributes -d megaraid5,/dev/sda -dbj /etc/nagios-plugins/config/check_smartdb.json -O 'sat+'`

Output 

`Error: the following device(s) were not found in the smartdb JSON file: megaraid5,/dev/sda`

**Comment by vlar** [comment]
Any more idea to sort it out ?

**Comment by gschoenberger** [comment]
Can you test my latest commit an post the output? Commit c1fe09c4e9508bec5acc19e66ebcc6f0d2d625ac
It should print the used smartctl command which is useful in most situations.
The we can check if the smartclt command is correct for you. If yes we have to check the DB JSON file in the next step. If not we have to modify the smartctl command!

THX - Georg

**Comment by vlar** [comment]
Hey thanks for such follow up. 

I have tried your last commit: 

`/usr/local/nagios/libexec/check_smart_attributes -d megaraid5,/dev/sda -dbj /etc/nagios-plugins/config/check_smartdb.json -O 'sat+'
OK (megaraid5) |'megaraid5_Airflow_Temperature_Cel'=28;50;60 'megaraid5_Temperature_Celsius'=28;50;60 'megaraid5_Available_Reservd_Space'=100;16;11 'megaraid5_Media_Wearout_Indicator'=100;16;6 'megaraid5_Total_LBAs_Written'=505240 'megaraid5_Total_LBAs_Read'=1167397`

I guess we are finally okay :). 
The output is different from others but I like this: OK (megaraid5)
