### ISSUE TITLE
Error adding SAMSUNG SSD SM841

### ISSUE THREAD

**Issue by wforumw** [thomas-krenn/check_smart_attributes#87]
Hi,
We have a Samsung SSD to monitor 
Device Model:     SAMSUNG SSD SM841 2.5" 7mm 128GB

How can I add this SSD to the json database?
The problem is the " in the middel of the name.
` expected while parsing array, at character offset 110 (before "7mm 128GB"],\n      ...") at ./check_smart_attributes line 205.`

Many thanks!!

**Comment by gschoenberger** [comment]
Can you also show us a "smartctl -a" of the device?

**Comment by wforumw** [comment]
=== START OF INFORMATION SECTION ===
Device Model:     SAMSUNG SSD SM841 2.5" 7mm 128GB
LU WWN Device Id: 5 002538 500000000
Firmware Version: DXM02D0Q
User Capacity:    128,035,676,160 bytes [128 GB]
Sector Size:      512 bytes logical/physical
Rotation Rate:    Solid State Device
Device is:        Not in smartctl database [for details use: -P showall]
ATA Version is:   ACS-2, ATA8-ACS T13/1699-D revision 4c
SATA Version is:  SATA 3.1, 6.0 Gb/s (current: 6.0 Gb/s)
SMART support is: Available - device has SMART capability.
SMART support is: Enabled

**Comment by gschoenberger** [comment]
Can you try to escape the double quotes in the JSON string?:
`SAMSUNG SSD SM841 2.5\" 7mm 128GB`

**Comment by wforumw** [comment]
Thanks, that worked!!
