### ISSUE TITLE
Support /dev/disk/by-id/nvme-* paths

### ISSUE THREAD

**Issue by KaiRo-at** [thomas-krenn/check_smart_attributes#89]
Right now, NVMe devices can only be only be addressed via the /dev/nvme* paths but not via their /dev/disk/by-id/nvme-* paths while other types of devices can use the nicer /dev/disk/by-id/ entries.

See e.g. this example (parts of serial number and perf data XXed out for privacy because those details are not relevant here):
```
# /usr/lib/nagios/plugins/check_smart_attributes -d /dev/disk/by-id/nvme-Samsung_SSD_970_EVO_Plus_1TB_S4EWNF0MXXXXXX -dbj /etc/monitoring-plugins/check_smartdb.json
Error: the following device(s) where not found in the smartdb JSON file: /dev/disk/by-id/nvme-Samsung_SSD_970_EVO_Plus_1TB_S4EWNF0MXXXXXX
# /usr/lib/nagios/plugins/check_smart_attributes -d /dev/nvme0n1 -dbj /etc/monitoring-plugins/check_smartdb.json
OK (nvme0n1) |'Temperature'=XX;50;60 'Available Spare'=XX;16;11 'Percentage Used'=XX;85;90 'Data Units Read'=XXXXX 'Data Units Written'=XXXXX 'Host Read Commands'=XXXXXXXXX 'Host Write Commands'=XXXXXXXXX 'Power Cycles'=XX 'Power On Hours'=XXX
```

**Comment by gschoenberger** [comment]
Can you test commit d2cccfe4403a99683bd000b5522a42491b5b2a91 ?

**Comment by tniedermeier** [comment]
Hello @KaiRo-at,
did you have any chance to test commit d2cccfe ?

Best regards,
Thomas

**Comment by KaiRo-at** [comment]
> Hello @KaiRo-at,
> did you have any chance to test commit [d2cccfe](https://github.com/thomas-krenn/check_smart_attributes/commit/d2cccfe4403a99683bd000b5522a42491b5b2a91) ?

Sorry, I missed that comment, it's on my radar now, I will look into that soon.

**Comment by KaiRo-at** [comment]
> Can you test commit [d2cccfe](https://github.com/thomas-krenn/check_smart_attributes/commit/d2cccfe4403a99683bd000b5522a42491b5b2a91) ?

OK, I applied that patch to the older version I have on my system as I couldn't get a current one to work easily due to the JSON changes (didn't want to go into getting an updated check_smartdb.json) - and long story short, it seems to work fine! \o/

Thanks for the work, now it just needs to make it into a release and then I hope my distro will pick it up as well ;-)
