### ISSUE TITLE
Detection error with a /dev/disk/by-id/* path

### ISSUE THREAD

**Issue by Josef-Friedrich** [thomas-krenn/check_smart_attributes#93]
I have multiple external USB hard disks connected to my Raspberry PI 4. 
If I specify the disks with sda, sdb etc. the plugin works fine. But on a reboot the order of the sda sdb disks is mixed. 
That's why I would like to use `/dev/disk/by-id/*` paths. Unfortunately the plugin cannot handle this path.

```
check_smart_attributes -dbj /etc/check_smartdb.json -d /dev/disk/by-id/usb-WD_Elements_10B8_57584431453235345A4B3654-0:0
```

```
Use of uninitialized value $currDevice in concatenation (.) or string at /usr/lib/nagios/plugins/check_smart_attributes line 232.
Use of uninitialized value $currDevice in concatenation (.) or string at /usr/lib/nagios/plugins/check_smart_attributes line 232.
...
Use of uninitialized value $1 in concatenation (.) or string at /usr/lib/nagios/plugins/check_smart_attributes line 934.
```

but `smartctl` can

```
smartctl -a /dev/disk/by-id/usb-WD_Elements_10B8_57584431453235345A4B3654-0:0
```

works fine

Thank you for this wonderful monitoring plugin

**Comment by gschoenberger** [comment]
Actually it should work.
Maybe the regex does not macht the USB devices?
`$devChecked->{'Path'} =~ m/^\/dev\/(?:disk\/by-id\/)?([A-Za-z0-9_\-,\.]+)$/;`

**Comment by Josef-Friedrich** [comment]
The `:` is missing in the regex

`$devChecked->{'Path'} =~ m/^\/dev\/(?:disk\/by-id\/)?([A-Za-z0-9_\-,\.:]+)$/;`

**Comment by gschoenberger** [comment]
Done by commit 7759793d4c17b8923d10f995803433ae3246c9f7
Can you test it?

**Comment by Josef-Friedrich** [comment]
That was fast. It worked like a charm. Thank you.
